server:
  port: 8347
  maxHttpHeaderSize: 102400

logging:
  level:
    root: info

common-args:
  # 测试套件地址
  testBaseDir: /root/MsProf/testsets/
  # locust脚本地址
  locustExecutor: /root/MsProf/app/locustExec.py
  # har文件地址
  harDir: /root/MsProf/hars
  # API文件
  APIFile: /root/MsProf/API/API.json